# FIFA World Cup 2026: Full Tournament Predictions
By Karl Estampador :)

Simulates all 104 matches using the Elo-based model from `model.ipynb`.  
The higher-Elo team always advances.  
Third-place bracket allocation follows FIFA's official 495-combination lookup table.

In [1]:
# Load model functions and data
%run model.ipynb

48 teams in 2026-05-27 Elo snapshot
48 teams loaded; 48 FIFA ranks available
Alias map and Elo lookup ready.
  Spain                               Elo=2165
  USA                                 Elo=1721
  IR Iran                             Elo=1760
  Côte d'Ivoire                       Elo=1676
  Bosnia and Herzegovina              Elo=1594
  Iraq                                Elo=1607
  DR Congo                            Elo=1655
  Czechia                             Elo=1726
  Sweden                              Elo=1719
  Turkey                              Elo=1902
predict_winner and predict_score ready.

Match                               Winner                         Score
---------------------------------------------------------------------------
Spain vs Morocco                   Spain                          2-0  (Elo: 2165 vs 1822)
Argentina vs Jordan                    Argentina                      2-0  (Elo: 2113 vs 1690)
USA vs Turkey                    Turkey                         0-2  (Elo: 1902 vs 1721)
France vs Iraq                      France                         2-0  (Elo: 2081 vs 1607)

In [2]:
import pandas as pd
from pathlib import Path

DATA = Path('data')

# Load schedule and team registry
matches_df = pd.read_csv(DATA / 'matches.csv')
teams_df   = pd.read_csv(DATA / 'teams.csv')

# Build team-ID -> name lookup
id_to_name: dict[int, str] = dict(zip(teams_df['id'], teams_df['team_name']))
name_to_group: dict[str, str] = dict(zip(teams_df['team_name'], teams_df['group_letter']))

alloc_df = pd.read_csv(DATA / 'third_place_allocation.csv')

print(f'{len(matches_df)} matches loaded | {len(teams_df)} teams | allocation table: {len(alloc_df)} rows')

104 matches loaded | 48 teams | allocation table: 495 rows

---
## 1. Group Stage Simulation

In [3]:
group_matches = matches_df[matches_df['stage_id'] == 1].copy()

gs_results = []   # list of dicts, one per group-stage match

for _, row in group_matches.iterrows():
    home = id_to_name[int(row['home_team_id'])]
    away = id_to_name[int(row['away_team_id'])]
    hg, ag = predict_score(home, away)
    winner, loser, _, _ = predict_winner(home, away)
    gs_results.append({
        'match':      int(row['match_number']),
        'group':      row['match_label'],
        'home':       home,
        'away':       away,
        'home_goals': hg,
        'away_goals': ag,
        'winner':     winner,
    })

gs_df = pd.DataFrame(gs_results)
print(f'{len(gs_df)} group-stage matches simulated')

72 group-stage matches simulated

### Group Stage Results

In [4]:
display_gs = gs_df[['match','group','home','home_goals','away_goals','away','winner']].copy()
display_gs.columns = ['Match','Group','Home','HG','AG','Away','Winner']

pd.set_option('display.max_rows', 80)
pd.set_option('display.width', 120)
pd.set_option('display.max_colwidth', 30)

display_gs

    Match    Group                    Home  HG  AG                    Away                  Winner
0       1  Group A                  Mexico   2   0            South Africa                  Mexico
1       2  Group A             South Korea   1   0                 Czechia             South Korea
2       3  Group B                  Canada   2   0  Bosnia and Herzegovina                  Canada
3       4  Group D                     USA   0   2                Paraguay                Paraguay
4       5  Group B                   Qatar   0   2             Switzerland             Switzerland
5       6  Group C                  Brazil   2   0                 Morocco                  Brazil
6       7  Group C                   Haiti   0   2                Scotland                Scotland
7       8  Group D               Australia   0   2                  Turkey                  Turkey
8       9  Group E                 Germany   2   0                 Curaçao                 Germany
9      10  Group F             Netherlands   2   0                   Japan             Netherlands
10     11  Group E           Côte d'Ivoire   0   2                 Ecuador                 Ecuador
11     12  Group F                  Sweden   2   0                 Tunisia                  Sweden
12     13  Group H                   Spain   2   0              Cabo Verde                   Spain
13     14  Group G                 Belgium   2   0                   Egypt                 Belgium
14     15  Group H            Saudi Arabia   0   2                 Uruguay                 Uruguay
15     16  Group G                 IR Iran   2   0             New Zealand                 IR Iran
16     17  Group I                  France   2   0                 Senegal                  France
17     18  Group I                    Iraq   0   2                  Norway                  Norway
18     19  Group J               Argentina   2   0                 Algeria               Argentina
19     20  Group J                 Austria   2   0                  Jordan                 Austria
20     21  Group K                Portugal   2   0                DR Congo                Portugal
21     22  Group L                 England   2   0                 Croatia                 England
22     23  Group L                   Ghana   0   2                  Panama                  Panama
23     24  Group K              Uzbekistan   0   2                Colombia                Colombia
24     25  Group A                 Czechia   2   0            South Africa                 Czechia
25     26  Group B             Switzerland   2   0  Bosnia and Herzegovina             Switzerland
26     27  Group B                  Canada   2   0                   Qatar                  Canada
27     28  Group A                  Mexico   2   0             South Korea                  Mexico
28     29  Group D                     USA   0   2               Australia               Australia
29     30  Group C                Scotland   0   2                 Morocco                 Morocco
30     31  Group C                  Brazil   2   0                   Haiti                  Brazil
31     32  Group D                  Turkey   2   0                Paraguay                  Turkey
32     33  Group F             Netherlands   2   0                  Sweden             Netherlands
33     34  Group E                 Germany   2   0           Côte d'Ivoire                 Germany
34     35  Group E                 Ecuador   2   0                 Curaçao                 Ecuador
35     36  Group F                 Tunisia   0   2                   Japan                   Japan
36     37  Group H                   Spain   2   0            Saudi Arabia                   Spain
37     38  Group G                 Belgium   2   0                 IR Iran                 Belgium
38     39  Group H                 Uruguay   2   0              Cabo Verde                 Uruguay
39     40  Group G             New Zealand   0   2                   Egypt                   Egypt
40     41  Group J               Argentina   2   0                 Austria               Argentina
41     42  Group I                  France   2   0                    Iraq                  France
42     43  Group I                  Norway   1   0                 Senegal                  Norway
43     44  Group J                  Jordan   0   2                 Algeria                 Algeria
44     45  Group K                Portugal   2   0              Uzbekistan                Portugal
45     46  Group L                 England   2   0                   Ghana                 England
46     47  Group L                  Panama   0   2                 Croatia                 Croatia
47     48  Group K                Colombia   2   0                DR Congo                Colombia
48     49  Group B             Switzerland   2   0                  Canada             Switzerland
49     50  Group B  Bosnia and Herzegovina   2   0                   Qatar  Bosnia and Herzegovina
50     51  Group C                Scotland   0   2                  Brazil                  Brazil
51     52  Group C                 Morocco   2   0                   Haiti                 Morocco
52     53  Group A                 Czechia   0   2                  Mexico                  Mexico
53     54  Group A            South Africa   0   2             South Korea             South Korea
54     55  Group E                 Curaçao   0   2           Côte d'Ivoire           Côte d'Ivoire
55     56  Group E                 Ecuador   1   0                 Germany                 Ecuador
56     57  Group F                   Japan   2   0                  Sweden                   Japan
57     58  Group F                 Tunisia   0   2             Netherlands             Netherlands
58     59  Group D                  Turkey   2   0                     USA                  Turkey
59     60  Group D                Paraguay   2   0               Australia                Paraguay
60     61  Group I                  Norway   0   2                  France                  France
61     62  Group I                 Senegal   2   0                    Iraq                 Senegal
62     63  Group H              Cabo Verde   0   1            Saudi Arabia            Saudi Arabia
63     64  Group H                 Uruguay   0   2                   Spain                   Spain
64     65  Group G                   Egypt   0   2                 IR Iran                 IR Iran
65     66  Group G             New Zealand   0   2                 Belgium                 Belgium
66     67  Group L                  Panama   0   2                 England                 England
67     68  Group L                 Croatia   2   0                   Ghana                 Croatia
68     69  Group K                Colombia   0   1                Portugal                Portugal
69     70  Group K                DR Congo   0   2              Uzbekistan              Uzbekistan
70     71  Group J                 Algeria   0   2                 Austria                 Austria
71     72  Group J                  Jordan   0   2               Argentina               Argentina

---
## 2. Group Standings

In [ ]:
# build standings table for all 12 groups from group-stage results
def build_standings(gs_df: pd.DataFrame) -> pd.DataFrame:
    """
    Tiebreakers (when points equal):
      1. Goal difference (all group games)
      2. Goals scored (all group games)
      3. Elo rating (proxy for FIFA rank)
    """
    stats: dict[str, dict] = {}

    for _, r in gs_df.iterrows():
        for team, gf, ga in [
            (r['home'], r['home_goals'], r['away_goals']),
            (r['away'], r['away_goals'], r['home_goals']),
        ]:
            if team not in stats:
                stats[team] = {'gp': 0, 'w': 0, 'l': 0, 'gf': 0, 'ga': 0, 'pts': 0}
            s = stats[team]
            s['gp'] += 1
            s['gf'] += gf
            s['ga'] += ga
            if gf > ga:
                s['w']   += 1
                s['pts'] += 3
            else:
                s['l'] += 1

    rows = []
    for team, s in stats.items():
        rows.append({
            'team':  team,
            'group': name_to_group[team],
            'gp':    s['gp'],
            'w':     s['w'],
            'l':     s['l'],
            'gf':    s['gf'],
            'ga':    s['ga'],
            'gd':    s['gf'] - s['ga'],
            'pts':   s['pts'],
            'elo':   get_elo(team),
        })

    df = pd.DataFrame(rows)
    df = df.sort_values(
        ['group', 'pts', 'gd', 'gf', 'elo'],
        ascending=[True, False, False, False, False]
    ).reset_index(drop=True)

    # Add rank within group (1-4)
    df['rank'] = df.groupby('group').cumcount() + 1
    return df


standings = build_standings(gs_df)
print(standings[['group','rank','team','gp','w','l','gf','ga','gd','pts','elo']].to_string(index=False))

group  rank                   team  gp  w  l  gf  ga  gd  pts  elo
    A     1                 Mexico   3  3  0   6   0   6    9 1860
    A     2            South Korea   3  2  1   3   2   1    6 1752
    A     3                Czechia   3  1  2   2   3  -1    3 1726
    A     4           South Africa   3  0  3   0   6  -6    0 1524
    B     1            Switzerland   3  3  0   6   0   6    9 1889
    B     2                 Canada   3  2  1   4   2   2    6 1784
    B     3 Bosnia and Herzegovina   3  1  2   2   4  -2    3 1594
    B     4                  Qatar   3  0  3   0   6  -6    0 1425
    C     1                 Brazil   3  3  0   6   0   6    9 1984
    C     2                Morocco   3  2  1   4   2   2    6 1822
    C     3               Scotland   3  1  2   2   4  -2    3 1767
    C     4                  Haiti   3  0  3   0   6  -6    0 1532
    D     1                 Turkey   3  3  0   6   0   6    9 1902
    D     2               Paraguay   3  2  1   4   2   2    6 1833
    D     3              Australia   3  1  2   2   4  -2    3 1783
    D     4                    USA   3  0  3   0   6  -6    0 1721
    E     1                Ecuador   3  3  0   5   0   5    9 1933
    E     2                Germany   3  2  1   4   1   3    6 1923
    E     3          Côte d'Ivoire   3  1  2   2   4  -2    3 1676
    E     4                Curaçao   3  0  3   0   6  -6    0 1436
    F     1            Netherlands   3  3  0   6   0   6    9 1961
    F     2                  Japan   3  2  1   4   2   2    6 1904
    F     3                 Sweden   3  1  2   2   4  -2    3 1719
    F     4                Tunisia   3  0  3   0   6  -6    0 1636
    G     1                Belgium   3  3  0   6   0   6    9 1867
    G     2                IR Iran   3  2  1   4   2   2    6 1760
    G     3                  Egypt   3  1  2   2   4  -2    3 1689
    G     4            New Zealand   3  0  3   0   6  -6    0 1585
    H     1                  Spain   3  3  0   6   0   6    9 2165
    H     2                Uruguay   3  2  1   4   2   2    6 1892
    H     3           Saudi Arabia   3  1  2   1   4  -3    3 1568
    H     4             Cabo Verde   3  0  3   0   5  -5    0 1549
    I     1                 France   3  3  0   6   0   6    9 2081
    I     2                 Norway   3  2  1   3   2   1    6 1912
    I     3                Senegal   3  1  2   2   3  -1    3 1878
    I     4                   Iraq   3  0  3   0   6  -6    0 1607
    J     1              Argentina   3  3  0   6   0   6    9 2113
    J     2                Austria   3  2  1   4   2   2    6 1827
    J     3                Algeria   3  1  2   2   4  -2    3 1743
    J     4                 Jordan   3  0  3   0   6  -6    0 1690
    K     1               Portugal   3  3  0   5   0   5    9 1984
    K     2               Colombia   3  2  1   4   1   3    6 1975
    K     3             Uzbekistan   3  1  2   2   4  -2    3 1727
    K     4               DR Congo   3  0  3   0   6  -6    0 1655
    L     1                England   3  3  0   6   0   6    9 2020
    L     2                Croatia   3  2  1   4   2   2    6 1930
    L     3                 Panama   3  1  2   2   4  -2    3 1737
    L     4                  Ghana   3  0  3   0   6  -6    0 1503

### Group Standings Summary (Qualification Status)

In [ ]:
def qualify_label(rank: int, team: str, qualified_thirds: set) -> str:
    if rank == 1:
        return '✓ 1st'
    elif rank == 2:
        return '✓ 2nd'
    elif rank == 3:
        return '? 3rd'
    else:
        return '✗ Out'

disp = standings[['group','rank','team','pts','gd','gf','elo']].copy()
disp['status'] = disp['rank'].map({1:'✓ 1st', 2:'✓ 2nd', 3:'→ TBD 3rd', 4:'✗ Eliminated'})
disp.columns = ['Group','Rank','Team','Pts','GD','GF','Elo','Status']
disp

   Group  Rank                    Team  Pts  GD  GF   Elo        Status
0      A     1                  Mexico    9   6   6  1860         ✓ 1st
1      A     2             South Korea    6   1   3  1752         ✓ 2nd
2      A     3                 Czechia    3  -1   2  1726     → TBD 3rd
3      A     4            South Africa    0  -6   0  1524  ✗ Eliminated
4      B     1             Switzerland    9   6   6  1889         ✓ 1st
5      B     2                  Canada    6   2   4  1784         ✓ 2nd
6      B     3  Bosnia and Herzegovina    3  -2   2  1594     → TBD 3rd
7      B     4                   Qatar    0  -6   0  1425  ✗ Eliminated
8      C     1                  Brazil    9   6   6  1984         ✓ 1st
9      C     2                 Morocco    6   2   4  1822         ✓ 2nd
10     C     3                Scotland    3  -2   2  1767     → TBD 3rd
11     C     4                   Haiti    0  -6   0  1532  ✗ Eliminated
12     D     1                  Turkey    9   6   6  1902         ✓ 1st
13     D     2                Paraguay    6   2   4  1833         ✓ 2nd
14     D     3               Australia    3  -2   2  1783     → TBD 3rd
15     D     4                     USA    0  -6   0  1721  ✗ Eliminated
16     E     1                 Ecuador    9   5   5  1933         ✓ 1st
17     E     2                 Germany    6   3   4  1923         ✓ 2nd
18     E     3           Côte d'Ivoire    3  -2   2  1676     → TBD 3rd
19     E     4                 Curaçao    0  -6   0  1436  ✗ Eliminated
20     F     1             Netherlands    9   6   6  1961         ✓ 1st
21     F     2                   Japan    6   2   4  1904         ✓ 2nd
22     F     3                  Sweden    3  -2   2  1719     → TBD 3rd
23     F     4                 Tunisia    0  -6   0  1636  ✗ Eliminated
24     G     1                 Belgium    9   6   6  1867         ✓ 1st
25     G     2                 IR Iran    6   2   4  1760         ✓ 2nd
26     G     3                   Egypt    3  -2   2  1689     → TBD 3rd
27     G     4             New Zealand    0  -6   0  1585  ✗ Eliminated
28     H     1                   Spain    9   6   6  2165         ✓ 1st
29     H     2                 Uruguay    6   2   4  1892         ✓ 2nd
30     H     3            Saudi Arabia    3  -3   1  1568     → TBD 3rd
31     H     4              Cabo Verde    0  -5   0  1549  ✗ Eliminated
32     I     1                  France    9   6   6  2081         ✓ 1st
33     I     2                  Norway    6   1   3  1912         ✓ 2nd
34     I     3                 Senegal    3  -1   2  1878     → TBD 3rd
35     I     4                    Iraq    0  -6   0  1607  ✗ Eliminated
36     J     1               Argentina    9   6   6  2113         ✓ 1st
37     J     2                 Austria    6   2   4  1827         ✓ 2nd
38     J     3                 Algeria    3  -2   2  1743     → TBD 3rd
39     J     4                  Jordan    0  -6   0  1690  ✗ Eliminated
40     K     1                Portugal    9   5   5  1984         ✓ 1st
41     K     2                Colombia    6   3   4  1975         ✓ 2nd
42     K     3              Uzbekistan    3  -2   2  1727     → TBD 3rd
43     K     4                DR Congo    0  -6   0  1655  ✗ Eliminated
44     L     1                 England    9   6   6  2020         ✓ 1st
45     L     2                 Croatia    6   2   4  1930         ✓ 2nd
46     L     3                  Panama    3  -2   2  1737     → TBD 3rd
47     L     4                   Ghana    0  -6   0  1503  ✗ Eliminated

---
## 3. Third-Place Team Ranking

All 12 third-place finishers are ranked by: points → GD → GF → Elo.  
The top 8 advance to the Round of 32.

In [7]:
thirds = standings[standings['rank'] == 3].sort_values(
    ['pts', 'gd', 'gf', 'elo'],
    ascending=[False, False, False, False]
).reset_index(drop=True)

thirds['third_rank'] = range(1, len(thirds) + 1)
thirds['advances'] = thirds['third_rank'] <= 8

print('All third-place teams ranked (top 8 advance):\n')
display_thirds = thirds[['third_rank','group','team','pts','gd','gf','elo','advances']].copy()
display_thirds.columns = ['Rank','Group','Team','Pts','GD','GF','Elo','Advances']
display_thirds

All third-place teams ranked (top 8 advance):

    Rank Group                    Team  Pts  GD  GF   Elo  Advances
0      1     I                 Senegal    3  -1   2  1878      True
1      2     A                 Czechia    3  -1   2  1726      True
2      3     D               Australia    3  -2   2  1783      True
3      4     C                Scotland    3  -2   2  1767      True
4      5     J                 Algeria    3  -2   2  1743      True
5      6     L                  Panama    3  -2   2  1737      True
6      7     K              Uzbekistan    3  -2   2  1727      True
7      8     F                  Sweden    3  -2   2  1719      True
8      9     G                   Egypt    3  -2   2  1689     False
9     10     E           Côte d'Ivoire    3  -2   2  1676     False
10    11     B  Bosnia and Herzegovina    3  -2   2  1594     False
11    12     H            Saudi Arabia    3  -3   1  1568     False

---
## 4. Third-Place Bracket Allocation

The 8 qualifying group letters are sorted and looked up in FIFA's official 495-row allocation table, which assigns each third-place team to a specific Round of 32 slot.

In [ ]:
# The 8 advancing third-place teams and their groups
qualifying_thirds = thirds[thirds['advances']]
qualifying_groups_letters = sorted(qualifying_thirds['group'].tolist())
combo_key = ''.join(qualifying_groups_letters)

print(f'Qualifying third-place groups: {qualifying_groups_letters}')
print(f'Combination key: {combo_key}')

alloc_row = alloc_df[alloc_df['qualifying_groups'] == combo_key]

if alloc_row.empty:
    raise ValueError(f'No allocation row found for combination: {combo_key}')

alloc_row = alloc_row.iloc[0]

# Map: match_number -> which group's 3rd-place team plays there
third_slot: dict[int, str] = {}
for col in ['match_75', 'match_78', 'match_79', 'match_80', 'match_81', 'match_82', 'match_85', 'match_88']:
    match_num = int(col.split('_')[1])
    group_letter = alloc_row[col].replace('3', '')
    third_slot[match_num] = group_letter

# Build lookup: group letter → team name (for qualifying thirds)
group_to_third_team: dict[str, str] = dict(zip(qualifying_thirds['group'], qualifying_thirds['team']))

print('\nThird-place match assignments:')
for match_num, grp in sorted(third_slot.items()):
    team = group_to_third_team.get(grp, f'[Group {grp} 3rd]')
    print(f'  Match {match_num}: 3rd place from Group {grp} → {team}')

Qualifying third-place groups: ['A', 'C', 'D', 'F', 'I', 'J', 'K', 'L']
Combination key: ACDFIJKL

Third-place match assignments:
  Match 75: 3rd place from Group D → Australia
  Match 78: 3rd place from Group F → Sweden
  Match 79: 3rd place from Group C → Scotland
  Match 80: 3rd place from Group K → Uzbekistan
  Match 81: 3rd place from Group A → Czechia
  Match 82: 3rd place from Group I → Senegal
  Match 85: 3rd place from Group J → Algeria
  Match 88: 3rd place from Group L → Panama

---
## 5. Knockout Bracket Simulation

Round of 32 → Round of 16 → Quarterfinals → Semifinals → Bronze Final → Final

In [ ]:
import re

# returns the team that finished in position `rank` in the given group
def get_group_finisher(rank: int, group: str) -> str:
    result = standings[(standings['group'] == group) & (standings['rank'] == rank)]
    if result.empty:
        raise ValueError(f'No rank-{rank} team in group {group}')
    return result.iloc[0]['team']

# resolves a bracket token like '1A' into a concrete team name
def resolve_team(token: str,
                 match_winners: dict[int, str],
                 match_losers: dict[int, str]) -> str:
    # Winner of match N
    m = re.match(r'^W(\d+)$', token)
    if m:
        mn = int(m.group(1))
        return match_winners[mn]

    # Runner-up (loser) of match N
    m = re.match(r'^RU(\d+)$', token)
    if m:
        mn = int(m.group(1))
        return match_losers[mn]

    # Group finisher: '1A', '2F', etc.
    m = re.match(r'^([12])([A-L])$', token)
    if m:
        return get_group_finisher(int(m.group(1)), m.group(2))

    # Third-place slot: '3ABCDF' (match number determines which group's 3rd)
    # The calling code handles this separately via third_slot
    raise ValueError(f'Cannot resolve token: {token}')


def parse_label_tokens(label: str) -> tuple[str, str]:
    """Split a match_label like '1E vs 3ABCDF' into two raw tokens."""
    parts = label.strip().split(' vs ')
    if len(parts) != 2:
        raise ValueError(f'Unexpected label format: {label}')
    return parts[0].strip(), parts[1].strip()


# Run knockout bracket
match_winners: dict[int, str] = {}   # match_number -> winner team name
match_losers:  dict[int, str] = {}   # match_number-> loser team name (for bronze)

ko_matches = matches_df[matches_df['stage_id'] >= 2].sort_values('match_number')

stage_names = {2: 'Round of 32', 3: 'Round of 16', 4: 'Quarterfinals',
               5: 'Semifinals', 6: 'Bronze Final', 7: 'Final'}

ko_results = []

for _, row in ko_matches.iterrows():
    mn    = int(row['match_number'])
    stage = int(row['stage_id'])
    label = row['match_label']

    tok_a, tok_b = parse_label_tokens(label)

    # Resolve third-place tokens (e.g. '3ABCDF') using allocation table
    def resolve_with_third(tok):
        if re.match(r'^3[A-L]+$', tok):
            grp = third_slot[mn]
            return group_to_third_team[grp]
        return resolve_team(tok, match_winners, match_losers)

    team_a = resolve_with_third(tok_a)
    team_b = resolve_with_third(tok_b)

    winner, loser, w_elo, l_elo = predict_winner(team_a, team_b)
    match_winners[mn] = winner
    match_losers[mn]  = loser

    ko_results.append({
        'match':  mn,
        'stage':  stage_names[stage],
        'team_a': team_a,
        'team_b': team_b,
        'winner': winner,
        'loser':  loser,
        'w_elo':  int(w_elo),
        'l_elo':  int(l_elo),
    })

ko_df = pd.DataFrame(ko_results)
print(f'{len(ko_df)} knockout matches resolved')

32 knockout matches resolved

---
## 6. Results Output

### Round of 32

In [10]:
def show_stage(stage_name: str):
    df = ko_df[ko_df['stage'] == stage_name][['match','team_a','team_b','winner','w_elo','l_elo']].copy()
    df.columns = ['Match', 'Team A', 'Team B', 'Winner', 'Winner Elo', 'Loser Elo']
    return df.reset_index(drop=True)

show_stage('Round of 32')

    Match       Team A      Team B       Winner  Winner Elo  Loser Elo
0      73  South Korea      Canada       Canada        1784       1752
1      74       Brazil       Japan       Brazil        1984       1904
2      75      Ecuador   Australia      Ecuador        1933       1783
3      76  Netherlands     Morocco  Netherlands        1961       1822
4      77      Germany      Norway      Germany        1923       1912
5      78       France      Sweden       France        2081       1719
6      79       Mexico    Scotland       Mexico        1860       1767
7      80      England  Uzbekistan      England        2020       1727
8      81      Belgium     Czechia      Belgium        1867       1726
9      82       Turkey     Senegal       Turkey        1902       1878
10     83        Spain     Austria        Spain        2165       1827
11     84     Colombia     Croatia     Colombia        1975       1930
12     85  Switzerland     Algeria  Switzerland        1889       1743
13     86     Paraguay     IR Iran     Paraguay        1833       1760
14     87    Argentina     Uruguay    Argentina        2113       1892
15     88     Portugal      Panama     Portugal        1984       1737

### Round of 16

In [11]:
show_stage('Round of 16')

   Match       Team A     Team B     Winner  Winner Elo  Loser Elo
0     89       Canada    Ecuador    Ecuador        1933       1784
1     90       Brazil    Germany     Brazil        1984       1923
2     91  Netherlands     France     France        2081       1961
3     92       Mexico    England    England        2020       1860
4     93        Spain   Colombia      Spain        2165       1975
5     94      Belgium     Turkey     Turkey        1902       1867
6     95     Paraguay   Portugal   Portugal        1984       1833
7     96  Switzerland  Argentina  Argentina        2113       1889

### Quarterfinals

In [12]:
show_stage('Quarterfinals')

   Match    Team A     Team B     Winner  Winner Elo  Loser Elo
0     97   Ecuador     Brazil     Brazil        1984       1933
1     98     Spain     Turkey      Spain        2165       1902
2     99    France    England     France        2081       2020
3    100  Portugal  Argentina  Argentina        2113       1984

### Semifinals

In [13]:
show_stage('Semifinals')

   Match  Team A     Team B     Winner  Winner Elo  Loser Elo
0    101  Brazil      Spain      Spain        2165       1984
1    102  France  Argentina  Argentina        2113       2081

### Bronze Final (3rd Place)

In [14]:
show_stage('Bronze Final')

   Match  Team A  Team B  Winner  Winner Elo  Loser Elo
0    103  Brazil  France  France        2081       1984

---
## 🏆 Final

In [15]:
final_row = ko_df[ko_df['stage'] == 'Final'].iloc[0]
champion  = final_row['winner']
runner_up = final_row['loser']

print('=' * 60)
print(f'  FINAL  (Match {final_row["match"]})')
print(f'  {final_row["team_a"]:25s} vs  {final_row["team_b"]}')
print(f'  Winner:     {champion}')
print(f'  Runner-up:  {runner_up}')
print('=' * 60)
print(f'\n  2026 FIFA WORLD CUP CHAMPION: {champion.upper()}')
print(f'  (Elo: {int(final_row["w_elo"])}) ')

============================================================
  FINAL  (Match 104)
  Spain                     vs  Argentina
  Winner:     Spain
  Runner-up:  Argentina
============================================================

  2026 FIFA WORLD CUP CHAMPION: SPAIN
  (Elo: 2165)

---
## Full Knockout Bracket Summary

In [16]:
for stage in ['Round of 32', 'Round of 16', 'Quarterfinals', 'Semifinals', 'Bronze Final', 'Final']:
    subset = ko_df[ko_df['stage'] == stage]
    print(f'\n{stage.upper()}')
    print('-' * 60)
    for _, r in subset.iterrows():
        print(f'  Match {r["match"]:3d}: {r["team_a"]:26s} vs {r["team_b"]:26s}  →  {r["winner"]}')

ROUND OF 32
------------------------------------------------------------
  Match  73: South Korea                vs Canada                      →  Canada
  Match  74: Brazil                     vs Japan                       →  Brazil
  Match  75: Ecuador                    vs Australia                   →  Ecuador
  Match  76: Netherlands                vs Morocco                     →  Netherlands
  Match  77: Germany                    vs Norway                      →  Germany
  Match  78: France                     vs Sweden                      →  France
  Match  79: Mexico                     vs Scotland                    →  Mexico
  Match  80: England                    vs Uzbekistan                  →  England
  Match  81: Belgium                    vs Czechia                     →  Belgium
  Match  82: Turkey                     vs Senegal                     →  Turkey
  Match  83: Spain                      vs Austria                     →  Spain
  Match  84: Colombia                   vs Croatia                     →  Colombia
  Match  85: Switzerland                vs Algeria                     →  Switzerland
  Match  86: Paraguay                   vs IR Iran                     →  Paraguay
  Match  87: Argentina                  vs Uruguay                     →  Argentina
  Match  88: Portugal                   vs Panama                      →  Portugal

ROUND OF 16
------------------------------------------------------------
  Match  89: Canada                     vs Ecuador                     →  Ecuador
  Match  90: Brazil                     vs Germany                     →  Brazil
  Match  91: Netherlands                vs France                      →  France
  Match  92: Mexico                     vs England                     →  England
  Match  93: Spain                      vs Colombia                    →  Spain
  Match  94: Belgium                    vs Turkey                      →  Turkey
  Match  95: Paraguay                   vs Portugal                    →  Portugal
  Match  96: Switzerland                vs Argentina                   →  Argentina

QUARTERFINALS
------------------------------------------------------------
  Match  97: Ecuador                    vs Brazil                      →  Brazil
  Match  98: Spain                      vs Turkey                      →  Spain
  Match  99: France                     vs England                     →  France
  Match 100: Portugal                   vs Argentina                   →  Argentina

SEMIFINALS
------------------------------------------------------------
  Match 101: Brazil                     vs Spain                       →  Spain
  Match 102: France                     vs Argentina                   →  Argentina

BRONZE FINAL
------------------------------------------------------------
  Match 103: Brazil                     vs France                      →  France

FINAL
------------------------------------------------------------
  Match 104: Spain                      vs Argentina                   →  Spain